### ISSUE TITLE
Delegate method never called

### ISSUE THREAD

**Issue by ARGAMX** [davbeck/TNKImagePickerController#30]
TNKImagePickerControllerDelegate method never called
`- (void)imagePickerController:(TNKImagePickerController *)picker`
until changed
`TNKImagePickerController *picker = [[TNKImagePickerController alloc] init];`
`picker.delegate = self;`
to
`
TNKImagePickerController *picker = [[TNKImagePickerController alloc] init];
picker.pickerDelegate = self;`

**Comment by davbeck** [comment]
That is correct. Those methods are part of the `TNKImagePickerControllerDelegate` protocol. Because `TNKImagePickerController` inherits from `UIPageViewController`, `delegate` already refers to the page view controller delegate, which `TNKImagePickerController` expects to be set to itself.

**Comment by ARGAMX** [comment]
So manual provided under section 'Usage' in README.md is not working by this reason.
It that correct too?
I think at least manual should be corrected.
